version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres1
    ports:
      - "5209:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: staff_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - staff-network

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "3209:3209"
    depends_on:
      - postgres
    networks:
      - staff-network

  hr-staff:
    build:
      context: ./HR-staff
    container_name: hr-staff
    ports:
      - "8018:80"
    depends_on:
      - backend
    networks:
      - staff-network

volumes:
  postgres_data:

networks:
  staff-network:

